'use client';
import {useEffect,useState,useMemo} from 'react';
import {AllocationCharts} from './charts';
import {Holdings} from './holdings';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Plus,RefreshCw,Download,ArrowUpRight,ShieldCheck,TriangleAlert,Wallet} from 'lucide-react';
import {feeKeys,normalizeNote,type Note,type Trade,type FeeKey,consolidate} from '@/lib/ledger';
type Quote={asset:string;price:number;at:string;name?:string;symbol?:string;updated?:string};
type Portfolio=ReturnType<typeof consolidate>&{notes:Note[];quotes:Quote[]};
const labels:Record<FeeKey,string>={settlement:'Liquidação / B3',exchange:'Emolumentos',brokerage:'Corretagem',iss:'ISS',irrf:'IRRF'};
const money=(c:number|null|undefined)=>c==null?'A conferir':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100);
const number=(n:number)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:8}).format(n);
const date=(s:string)=>s.slice(0,10).split('-').reverse().join('/');
function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
const emptyTrade:Trade={asset:'',category:'Ação',side:'buy',quantity:'',price:''};
function blankNote():Note{return {id:crypto.randomUUID(),number:'',broker:'',date:new Date().toISOString().slice(0,10),kind:'variable',fees:{settlement:'0',exchange:'0',brokerage:'0',iss:'0',irrf:'0'},trades:[{...emptyTrade}]};}
export default function PortfolioApp({name}:{name:string}){
 const [data,setData]=useState<Portfolio|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('carteira'),[filter]=useState('Todas'),[search,setSearch]=useState(''),[draft,setDraft]=useState<Note|null>(null),[formError,setFormError]=useState('');
 const [quick,setQuick]=useState(false),[assetClass,setAssetClass]=useState('Todas');
 async function load(){const r=await fetch('/api/portfolio');const j=await r.json() as Portfolio & {error:string};if(!r.ok)throw new Error(j.error);setData(j);setError('');}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;
  if(!context)return;const lifecycle=new AbortController();
  try{context.registerTool({name:'show_portfolio_view',description:'Abre uma tela do consolidador sem alterar movimentações.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['analise','carteira','movimentacoes','conferencia']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const v=(input as {view:string})?.view;if(!['analise','carteira','movimentacoes','conferencia'].includes(v))throw new Error('Tela inválida');setTab(v);return {view:v};}},{signal:lifecycle.signal});}catch{ /* optional browser capability */ }
  return()=>lifecycle.abort();
 },[]);
 async function act(action:string,note?:Note){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/portfolio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,note})});const j=await r.json() as {error:string;message:string};if(!r.ok)throw new Error(j.error);await load();setMessage(j.message);setDraft(null);}catch(e){if(note)setFormError((e as Error).message);else setError((e as Error).message);}finally{setBusy(false);}}
 async function market(){setBusy(true);setMessage('');try{const r=await fetch('/api/market',{method:'POST'});const j=await r.json() as {error:string;message:string};if(!r.ok)throw new Error(j.error);setMessage(j.message);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const selected=useMemo(()=>data?.positions.filter(p=>p.quantity>0&&(assetClass==='Todas'||p.category===assetClass))||[],[data,filter,assetClass]);
 const quoteMap=new Map(data?.quotes.map(q=>[q.asset,q]));
 const cost=selected.reduce((s,p)=>s+(p.cost||0),0);
 const allocation=useMemo(()=>{const groups=new Map<string,number>();for(const p of selected){const k=p.category==='Tesouro Direto'?'Renda fixa':p.category==='FII'?'Fundos imobiliários':'Ações';groups.set(k,(groups.get(k)||0)+(p.cost||0));}return [...groups].sort((a,b)=>b[1]-a[1]);},[selected]);
 const sectors=useMemo(()=>{const groups=new Map<string,number>();for(const p of selected.filter(p=>p.category==='Ação')){const k=p.sector||'Outros';groups.set(k,(groups.get(k)||0)+(p.cost||0));}return [...groups].sort((a,b)=>b[1]-a[1]);},[selected]);
 const valued=selected.filter(p=>p.reliable&&p.quantity>0&&quoteMap.has(p.asset));
 const marketTotal=valued.reduce((s,p)=>s+p.quantity*quoteMap.get(p.asset)!.price*100,0);
 const trades=(data?.movements||[]).filter(t=>(filter==='Todas'||t.broker===filter)&&(assetClass==='Todas'||t.category===assetClass)&&`${t.asset} ${t.number} ${t.broker}`.toLowerCase().includes(search.toLowerCase()));
 const filteredNotes=(data?.notes||[]).filter(n=>(filter==='Todas'||n.broker===filter)&&(assetClass==='Todas'||n.trades.some(t=>t.category===assetClass))&&`${n.number} ${n.broker} ${n.trades.map(t=>t.asset).join(' ')}`.toLowerCase().includes(search.toLowerCase()));
 let preview:ReturnType<typeof normalizeNote>=[];if(draft){try{preview=normalizeNote(draft);}catch{ /* draft is incomplete */ }}
 function updateTrade(i:number,patch:Partial<Trade>){setDraft(d=>d?{...d,trades:d.trades.map((t,j)=>j===i?{...t,...patch}:t)}:d);}
 function exportData(){if(!data)return;const blob=new Blob([JSON.stringify({format:'consolidador-v1',exportedAt:new Date().toISOString(),notes:data.notes,quotes:data.quotes},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='carteira-investimentos.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <main className="workspace"><header><div className="brand"><span className="brand-icon"><Wallet size={23}/></span><div><b>SAGRADO CAPITAL</b><small>Consolidador de Investimentos</small></div></div><div className="account"><ShieldCheck size={16}/><span>{name}</span><a href="/signout-with-chatgpt?return_to=/" target="_top">Sair</a></div></header>
 <div className="title-row"><div><p className="eyebrow">PAINEL DE INVESTIMENTOS</p><h1>Visão da carteira</h1><p className="muted">Ações, fundos imobiliários e Tesouro Direto.</p></div><Button onClick={()=>{setFormError('');setQuick(true);setDraft(blankNote());}}><Plus size={18}/>Nova movimentação</Button></div>
 {error&&<div role="alert" className="notice error">{error}<Button variant="outline" onClick={()=>load().catch(e=>setError(e.message))}>Tentar novamente</Button></div>}
 {message&&<p role="status" className="notice">{message}</p>}
 {!data&&!error&&<p role="status" className="surface">Carregando movimentações…</p>}
 {data&&!data.notes.length&&<section className="surface import"><div><p className="eyebrow">BASE INICIAL</p><h2>Importe seu histórico de investimentos</h2><p>140 movimentações em 91 documentos. As taxas serão rateadas pelo valor financeiro de cada operação, mantendo os valores originais para conferência.</p><p className="note">Fonte: CONTROLE DE AÇÕES - ITALO (version 2).xlsx · abas Dados e Tesouro Direto. Há saldos e valores líquidos que precisam ser conferidos.</p></div><Button disabled={busy} onClick={()=>act('import')}>{busy?'Importando…':'Importar minha planilha'}</Button></section>}
 {data&&data.notes.length>0&&<>
 <div className="toolbar"><div className="broker"><span>Classe de ativo</span><Choice label="Filtrar classe de ativo" value={assetClass} onChange={setAssetClass} options={['Todas','Ação','FII','Tesouro Direto']}/></div><div className="actions"><small className="note">{data.quotes.length?`Mercado em cache · ${new Date(Math.max(...data.quotes.map(q=>q.updated?Date.parse(q.updated):0))).toLocaleString('pt-BR')}`:'Sem cotações armazenadas'}</small><Button variant="outline" onClick={market} disabled={busy}><RefreshCw size={16}/>Atualizar cotações</Button><Button variant="outline" onClick={exportData}><Download size={16}/>Exportar dados</Button></div></div>
 <section className="cards"><article className="capital"><span>Custo das posições apuráveis</span><strong>{money(cost)}</strong><small>{selected.filter(p=>!p.reliable).length} posições com pendência excluídas</small></article><article><span>Valor de mercado parcial</span><strong>{valued.length?money(marketTotal):'Sem cotações'}</strong><small>{valued.length} de {selected.length} posições com cotação e saldo apurável</small></article><article><span>Movimentações registradas</span><strong>{number(trades.length)}</strong><small>{filteredNotes.length} notas e protocolos · {filter==='Todas'?'todas as corretoras':filter}</small></article></section>
 {data.issues.length>0&&<button className="review-strip" onClick={()=>setTab('conferencia')}><TriangleAlert size={18}/><span>{data.issues.length} pendências de conferência no histórico. Veja os documentos afetados.</span><ArrowUpRight size={18}/></button>}
 <Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="view-tabs"><TabsTrigger value="analise">Análise</TabsTrigger><TabsTrigger value="carteira">Carteira</TabsTrigger><TabsTrigger value="movimentacoes">Movimentações</TabsTrigger><TabsTrigger value="conferencia">Conferência</TabsTrigger></TabsList>
 <TabsContent value="analise"><AllocationCharts allocation={allocation} sectors={sectors}/><section className="surface"><h2>Base da análise</h2><p className="note">Distribuição calculada pelo custo de aquisição com taxas, não pelo valor de mercado. Renda fixa corresponde ao Tesouro Direto; renda variável reúne ações e FIIs. Posições com custo indeterminado não entram nos gráficos. A comparação com cotações é parcial e não representa rentabilidade total.</p></section></TabsContent><TabsContent value="carteira"><Holdings positions={selected} closed={data.closed.filter(p=>assetClass==='Todas'||p.category===assetClass)} realized={[...data.positions,...data.closed].filter(p=>assetClass==='Todas'||p.category===assetClass)} movements={data.movements} quotes={data.quotes}/></TabsContent>
 <TabsContent value="movimentacoes"><section className="surface"><div className="section-heading"><div><h2>Histórico de movimentações</h2><p className="note">Compras e vendas preservadas, taxas recalculadas por nota.</p></div><Input aria-label="Buscar ativo ou nota" placeholder="Buscar ativo, nota ou corretora" value={search} onChange={e=>setSearch(e.target.value)} className="search"/></div><Table><TableHeader><TableRow>{['Data','Ativo','Operação','Quantidade','Preço','Taxas¹','IRRF','Fluxo líquido'].map(v=><TableHead key={v}>{v}</TableHead>)}</TableRow></TableHeader><TableBody>{trades.map(t=><TableRow key={t.id}><TableCell>{date(t.date)}<small>{t.broker} · {t.number}</small></TableCell><TableCell><b>{t.asset}</b><small>{t.source}</small></TableCell><TableCell><span className={'pill '+t.side}>{t.side==='buy'?'Compra / aporte':'Venda / resgate'}</span></TableCell><TableCell className="numeric">{number(Number(t.quantity))}</TableCell><TableCell className="numeric">{money(Number(t.price)*100)}</TableCell><TableCell className="numeric">{money(t.costFees)}</TableCell><TableCell className="numeric">{money(t.fees.irrf)}</TableCell><TableCell className="numeric">{money(t.net)}</TableCell></TableRow>)}</TableBody></Table><p className="footnote">¹ Liquidação/B3, emolumentos, corretagem e ISS. IRRF mantido separado. Fluxo negativo indica pagamento, positivo indica recebimento; no Tesouro, IR/IOF ausentes da fonte não estão descontados.</p></section><section className="surface documents"><h2>Notas e protocolos</h2><p className="note">Edite o documento completo para recalcular todas as operações. A versão anterior permanece no histórico do banco.</p><div className="document-list">{filteredNotes.map(n=><button key={n.id} onClick={()=>{setFormError('');setQuick(false);setDraft(structuredClone(n));}}><span><b>{n.number}</b><small>{n.broker} · {date(n.date)} · {n.trades.length} operação(ões)</small></span><span>Editar →</span></button>)}</div></section></TabsContent>
 <TabsContent value="conferencia"><section className="surface"><h2>Conferência da base</h2><p className="note">Pendências de todas as corretoras. Nenhuma movimentação ausente é estimada automaticamente.</p><ul className="issues">{data.issues.map(i=><li key={i.key}><TriangleAlert size={17}/><span>{i.message}</span></li>)}</ul>{!data.issues.length&&<p>Nenhuma inconsistência automática de saldo ou líquido detectada. Confira os extratos e eventos societários antes de considerar o histórico completo.</p>}<div className="method"><h3>Como as taxas são distribuídas</h3><p>Cada tipo de taxa é dividido proporcionalmente a quantidade × preço dentro da mesma nota, data e corretora. Os centavos restantes são distribuídos pelas maiores frações, preservando o total de cada taxa. O IRRF é distribuído somente entre vendas.</p><h3>O que ainda depende de conferência</h3><p>Os totais foram reconstruídos a partir das taxas da planilha. Corretagem específica de uma operação exige conferência na nota original. Não são inferidos desdobramentos, grupamentos, trocas de ticker, rendimentos ou transferências. Cotações não alteram os preços das transações.</p><h3>Rastreabilidade</h3><p>Os lançamentos importados mantêm documento, aba, linha de origem e valores originais. Reimportar a mesma base preserva os documentos existentes.</p></div><Button variant="outline" disabled={busy} onClick={()=>act('import')}>Conferir novas entradas da base inicial</Button></section></TabsContent>
 </Tabs></>}
 <footer>Sagrado Capital <span>Consolidador de Investimentos · Cotações pela Brapi</span></footer>
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null);}}><DialogContent className="editor"><DialogHeader><DialogTitle>{draft?.version?'Editar documento':'Nova movimentação'}</DialogTitle><DialogDescription>{quick?'Registre uma compra ou venda. Se a nota tiver várias operações, use o modo completo para ratear as taxas.':'Cadastre todas as operações da nota e suas taxas totais. O rateio será automático.'}</DialogDescription></DialogHeader>{draft&&<form onSubmit={e=>{e.preventDefault();setFormError('');act('save',{...draft,number:draft.number.trim()||(quick?'MANUAL-'+draft.id.slice(0,8):'')});}}><Button type="button" variant="outline" disabled={!quick&&draft.trades.length>1} onClick={()=>setQuick(!quick)}>{quick?'Usar nota completa':'Usar lançamento rápido'}</Button><div className="form-grid"><label>Corretora<Input required maxLength={60} value={draft.broker} onChange={e=>setDraft({...draft,broker:e.target.value.toUpperCase()})}/></label><label>Nota / protocolo<Input required={!quick} placeholder={quick?'Opcional no lançamento rápido':'Número da nota'} maxLength={60} value={draft.number} onChange={e=>setDraft({...draft,number:e.target.value})}/></label><label>Data<Input type="date" required value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Mercado<Choice label="Mercado" value={draft.kind==='variable'?'Ações e FIIs':'Tesouro Direto'} options={['Ações e FIIs','Tesouro Direto']} onChange={v=>setDraft({...draft,kind:v==='Tesouro Direto'?'treasury':'variable',trades:draft.trades.map(t=>({...t,category:v==='Tesouro Direto'?'Tesouro Direto':'Ação'}))})}/></label></div>
 <h3>Operações da nota</h3>{draft.trades.map((t,i)=><div className="trade-editor" key={i}><div className="form-grid"><label>Ativo<Input required placeholder={draft.kind==='treasury'?'Tesouro Selic 2029':'PETR4'} value={t.asset} onChange={e=>updateTrade(i,{asset:draft.kind==='treasury'?e.target.value:e.target.value.toUpperCase()})}/></label><label>Categoria<Choice label="Categoria" value={t.category} options={draft.kind==='treasury'?['Tesouro Direto']:['Ação','FII']} onChange={v=>updateTrade(i,{category:v as Trade['category']})}/></label><label>Operação<Choice label="Operação" value={t.side==='buy'?'Compra / aporte':'Venda / resgate'} options={['Compra / aporte','Venda / resgate']} onChange={v=>updateTrade(i,{side:v==='Compra / aporte'?'buy':'sell'})}/></label><label>Quantidade<Input required type="number" step="0.00000001" min="0.00000001" value={t.quantity} onChange={e=>updateTrade(i,{quantity:e.target.value})}/></label><label>Preço unitário (R$)<Input required type="number" step="0.00000001" min="0.00000001" value={t.price} onChange={e=>updateTrade(i,{price:e.target.value})}/></label>{draft.kind==='treasury'&&<label>Vencimento<Input required type="date" value={t.maturity||''} onChange={e=>updateTrade(i,{maturity:e.target.value})}/></label>}</div><div className="trade-foot"><span>{preview[i]?`Taxas: ${money(preview[i].costFees)} · IRRF: ${money(preview[i].fees.irrf)}`:'Preencha quantidade e preço para ver o rateio.'}</span>{draft.trades.length>1&&<Button type="button" variant="ghost" onClick={()=>setDraft({...draft,trades:draft.trades.filter((_,j)=>j!==i)})}>Remover operação</Button>}</div></div>)}<Button hidden={quick} type="button" variant="outline" onClick={()=>setDraft({...draft,trades:[...draft.trades,{...emptyTrade,category:draft.kind==='treasury'?'Tesouro Direto':'Ação'}]})}><Plus size={16}/>Adicionar operação</Button><details open={!quick}><summary>Taxas totais do documento (R$) · opcionais no lançamento rápido</summary><div className="form-grid">{feeKeys.map(k=><label key={k}>{labels[k]}<Input required type="number" min="0" step="0.01" value={draft.fees[k]} onChange={e=>setDraft({...draft,fees:{...draft.fees,[k]:e.target.value}})}/></label>)}</div></details><p className="note">No Tesouro, informe a taxa B3 em “Liquidação / B3”. IR e IOF não estão contemplados nesta versão.</p>{formError&&<p role="alert" className="notice error">{formError}</p>}<div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setDraft(null)}>Cancelar</Button><Button type="submit" disabled={busy}>{busy?'Salvando…':'Salvar e recalcular'}</Button></div></form>}</DialogContent></Dialog>
 </main>;
}

