'use client';
import {ArrowUpRight,ArrowDownRight,ShieldCheck,Layers3,Focus} from 'lucide-react';
import {portfolioInsights,type Quote} from '@/lib/portfolio-insights';
import type {consolidate} from '@/lib/ledger';
type Data=ReturnType<typeof consolidate>&{quotes:Quote[]};
const money=(n:number)=>(n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const percent=(n:number)=>n.toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';
export function AnalysisPanel({data,category,overview=false,onReview}:{data:Data;category:string;overview?:boolean;onReview:()=>void}){
 const v=portfolioInsights(data,category);const largest=v.concentration[0];const oldest=v.quoteDates[0];
 return <div className="insight-panel"><section className="analysis-intro"><div><p className="eyebrow">{overview?'SEU PATRIMÔNIO, EM CONTEXTO':'LEITURA DA CARTEIRA'}</p><h2>{overview?'O que merece sua atenção hoje.':'Entenda o que compõe seu resultado.'}</h2><p>Uma leitura dos registros disponíveis, com cobertura e limitações explícitas.</p></div><span className="status-chip"><ShieldCheck size={15}/>Base registrada</span></section>
 <div className="insight-metrics"><article><span>Variação das posições com preço</span><strong className={v.change<0?'negative':'positive'}>{v.pricedCount?money(v.change):'Sem preços'}</strong><small>{v.changePercent!==null?percent(v.changePercent)+' sobre o custo dos mesmos ativos':'Sem base comparável'} · sem proventos</small></article><article><span>Resultado realizado apurável</span><strong>{money(v.realizedTotal)}</strong><small>FIFO gerencial · {v.pendingCount} ativos vendidos pendentes</small></article><article><span>Cobertura de preços</span><strong>{v.pricedCount}/{v.positions.length}<em> ativos</em></strong><small>{oldest?'Cotação mais antiga: '+oldest.slice(0,10).split('-').reverse().join('/'):'Ainda não há cotações disponíveis'}</small></article></div>
 <div className="insight-grid"><section className="surface"><div className="panel-heading"><Focus size={19}/><h3>Concentração do patrimônio</h3></div><p className="note">Os três maiores ativos representam <b>{percent(v.topThree*100)}</b> do custo apurável. {largest?`${largest.asset} é a maior posição (${percent(largest.weight*100)}).`:''}</p><div className="concentration-list">{v.concentration.slice(0,overview?5:10).map(p=><div key={p.asset}><div><b>{p.asset}</b><span>{percent(p.weight*100)}</span></div><div className="bar"><i style={{width:percent(p.weight*100)}}/></div><small>{money(p.cost)}</small></div>)}</div><p className="footnote">Base: custo registrado. Concentração mede exposição; não determina, sozinha, o risco ou a adequação da carteira.</p></section>
 <section className="surface"><div className="panel-heading"><Layers3 size={19}/><h3>O que os dados permitem concluir</h3></div><div className="reading-item"><b>{v.pricedCount===v.positions.length&&v.positions.length?'Preços cobrem as posições abertas':'Visão de mercado parcial'}</b><p>{v.pricedCount} de {v.positions.length} posições têm preço e custo comparáveis. A diferença usa somente esses ativos, evitando comparar um custo completo com um valor de mercado incompleto.</p></div><div className="reading-item"><b>{data.issues.length} alertas de conferência</b><p>Eventos e movimentações ausentes podem alterar quantidades, custos e resultados. Abra o documento de origem para corrigir os registros.</p><button onClick={onReview}>Revisar pendências <ArrowUpRight size={16}/></button></div><div className="reading-item"><b>Rentabilidade total ainda não disponível</b><p>O histórico não contém todos os proventos recebidos e fluxos externos. Por isso, não apresentamos TIR, retorno total ou comparação com CDI como se estivessem apurados.</p></div></section></div>
 {!overview&&<><section className="surface"><div className="panel-heading"><ArrowUpRight size={19}/><h3>Contribuição para a variação em aberto</h3></div><p className="note">Preço disponível menos custo dos mesmos ativos. Não inclui vendas, proventos ou impostos.</p><div className="contribution-list">{v.ranked.length?v.ranked.map(p=><div key={p.asset}><b>{p.asset}</b><span className={p.change<0?'negative':'positive'}>{p.change<0?<ArrowDownRight size={16}/>:<ArrowUpRight size={16}/>} {money(p.change)}</span><small>{p.percent===null?'—':percent(p.percent)}</small></div>):<p>Atualize as cotações para visualizar esta análise.</p>}</div></section><section className="surface"><h3>Compras e vendas ao longo do tempo</h3><p className="note">Volume bruto negociado por ano. Compras não equivalem necessariamente a aportes externos.</p><div className="activity-table"><table><thead><tr><th>Ano</th><th>Compras</th><th>Vendas / resgates</th><th>Despesas</th></tr></thead><tbody>{v.activity.map(([year,row])=><tr key={year}><td>{year}</td><td>{money(row.buys)}</td><td>{money(row.sells)}</td><td>{money(row.fees)}</td></tr>)}</tbody></table></div></section></>}
 </div>;
}
