'use client';
import Link from 'next/link';
import {LayoutDashboard,ArrowLeftRight,ClipboardCheck,Database,LogOut,RefreshCw} from 'lucide-react';
const pages=[{id:'dashboard',label:'Visão geral',Icon:LayoutDashboard},{id:'movimentacoes',label:'Movimentações',Icon:ArrowLeftRight},{id:'conferencia',label:'Conferência',Icon:ClipboardCheck}];
export type StorageInfo={provider:string;cloud:boolean;loadedAt:string;lastSavedAt:string|null};
export function AppSidebar({view,name,issues,storage}:{view:string;name:string;issues:number;storage?:StorageInfo}){
 async function signout(){if(storage?.cloud){const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});if(r.ok)window.location.assign(new URL('/login',window.location.origin).href);}else window.location.assign(new URL('/signout-with-chatgpt?return_to=/login',window.location.origin).href);}
 return <header className="app-navigation"><Link className="top-brand" href="/dashboard"><span className="brand-monogram">S</span><span>SAGRADO<small>CAPITAL</small></span></Link><nav aria-label="Navegação principal">{pages.map(({id,label,Icon})=><Link key={id} href={'/'+id} aria-current={view===id?'page':undefined}><Icon size={17}/><span>{label}</span>{id==='conferencia'&&issues>0&&<b>{issues}</b>}</Link>)}</nav><div className="top-account"><Database size={15}/><span title={storage?.provider}>{storage?.cloud?'Nuvem':'Local'}</span><span className="account-avatar">{name.slice(0,1).toUpperCase()}</span><button onClick={signout} aria-label="Sair da conta"><LogOut size={17}/></button></div></header>;
}
export function DataStatus({storage,onReload,busy}:{storage?:StorageInfo;onReload:()=>void;busy:boolean}){return <div className="data-status"><span><i className={storage?.cloud?'cloud':''}/>{storage?`${storage.provider} · lido às ${new Date(storage.loadedAt).toLocaleTimeString('pt-BR')}`:'Conectando ao banco'}{storage?.lastSavedAt&&<small>Última gravação: {new Date(storage.lastSavedAt).toLocaleString('pt-BR')}</small>}</span><button onClick={onReload} disabled={busy}><RefreshCw size={14}/> Recarregar dados</button></div>;}
