'use client';
import {useEffect,useMemo,useState} from 'react';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,ReferenceLine,Legend} from 'recharts';
import {ChevronRight,WalletCards,Landmark,TrendingUp,CircleDollarSign,TriangleAlert,Plus,RefreshCw} from 'lucide-react';
import type {consolidate,Movement} from '@/lib/ledger';
type Position=ReturnType<typeof consolidate>['positions'][number];
type Quote={asset:string;price:number;at:string;name?:string;logo?:string|null};
type Point={date:string;value:number};
type Benchmark={id:string;name:string;unit:'index'|'rate';frequency?:'daily'|'monthly'|'irregular';points:Point[];available:boolean;message?:string};
type AssetPoint={date:string;close:number;adjustedClose:number};
type History={series:Benchmark[];assetSeries:Record<string,AssetPoint[]>;updated?:string;messages?:string[];message?:string;error?:string};
type Data=ReturnType<typeof consolidate>&{quotes:Quote[];cashEvents?:Array<{netCents:number}>};
const palette=['#12665b','#cf9e51','#547899','#9a6e91','#879652'];
const currentDate=new Date();
const defaultEnd=currentDate.toISOString().slice(0,10);
const defaultStart=new Date(currentDate.getTime()-365*86400000).toISOString().slice(0,10);
const money=(n:number|null)=>n===null?'—':(n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const pct=(n:number|null)=>n===null?'—':n.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%';
const units=(n:number)=>n.toLocaleString('pt-BR',{maximumFractionDigits:8});
function ticketInitials(asset:string){const words=asset.trim().split(/\s+/).filter(Boolean);if(words.length>1)return (words[0][0]+words[1][0]).toUpperCase();return asset.replace(/[^A-Za-z]/g,'').slice(0,2).toUpperCase()||asset.slice(0,2).toUpperCase();}
function AssetIcon({asset,logo}:{asset:string;logo?:string|null}){return <span className="asset-logo" role="img" aria-label={`Identidade de ${asset}`} style={logo?{backgroundImage:`url("${logo.replaceAll('"','')}")`}:undefined}>{logo?'':ticketInitials(asset)}</span>;}
function normalizeBenchmark(series:Benchmark){
 if(!series.available||!series.points.length)return [];
 if(series.unit==='index'){const base=series.points[0].value;return series.points.map(p=>({date:p.date,value:(p.value/base-1)*100}));}
 let factor=1;return [...series.points].sort((a,b)=>a.date.localeCompare(b.date)).map(p=>{const rate=series.frequency==='daily'?Math.pow(1+p.value/100,1/252)-1:p.value/100;factor*=1+rate;return {date:p.date,value:(factor-1)*100};});
}
function portfolioSeries(movements:Movement[],prices:Record<string,AssetPoint[]>,adjusted:boolean,start:string,end:string){
 const priceByDate=new Map<string,Map<string,number>>();for(const [asset,rows] of Object.entries(prices))for(const row of rows){if(row.date<start||row.date>end)continue;const day=priceByDate.get(row.date)||new Map();day.set(asset,adjusted?row.adjustedClose:row.close);priceByDate.set(row.date,day);}
 const dates=[...priceByDate.keys()].sort();const ordered=[...movements].sort((a,b)=>a.date.localeCompare(b.date));const qty=new Map<string,number>();const last=new Map<string,number>();let cursor=0,previous=0,factor=1;const output:Point[]=[];
 for(const date of dates){let flow=0;while(cursor<ordered.length&&ordered[cursor].date<=date){const m=ordered[cursor++];const q=Number(m.quantity)*(m.side==='buy'?1:-1);qty.set(m.asset,(qty.get(m.asset)||0)+q);if(m.date>=start)flow+=m.side==='buy'?-m.net:-m.net;}
  for(const [asset,price] of priceByDate.get(date)!)last.set(asset,price);let value=0;for(const [asset,q] of qty){const price=last.get(asset);if(price&&q>0)value+=q*price*100;}
  if(previous>0){const daily=(value-previous-flow)/previous;if(Number.isFinite(daily)&&daily>-1)factor*=1+daily;}previous=value;if(value>0)output.push({date,value:(factor-1)*100});
 }
 return output;
}
function PortfolioList({positions,quotes,onDetails}:{positions:Position[];quotes:Quote[];onDetails:(asset:string)=>void}){
 const [category,setCategory]=useState('Todas');const qmap=new Map(quotes.map(q=>[q.asset,q]));
 const categories=['Ação','FII','Tesouro Direto'];const visible=positions.filter(p=>category==='Todas'||p.category===category);
 const groups=category==='Todas'?categories.map(name=>({name,rows:visible.filter(p=>p.category===name)})).filter(group=>group.rows.length):[{name:category,rows:visible}];
 return <section className="surface overview-portfolio"><div className="overview-section-head"><div><h2>Carteira</h2><p>Ativos como centros de movimentações, eventos e proventos.</p></div><span>{visible.length} ativos</span></div><div className="asset-tabs-inline">{['Todas',...categories].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c==='Todas'?'Todos':c}</button>)}</div><div className="overview-asset-scroll"><table><colgroup><col className="asset-column"/><col/><col/><col/><col/><col/></colgroup><thead><tr><th>Ativo</th><th>Qtd</th><th>Aplicado</th><th>Mercado</th><th>Resultado</th><th/></tr></thead>{groups.map(group=><tbody key={group.name}><tr className="asset-group-row"><th colSpan={6}><span className="group-name">{group.name}</span><span>{group.rows.length} ativos · {money(group.rows.reduce((sum,row)=>sum+(row.cost||0),0))} aplicados</span></th></tr>{group.rows.map(p=>{const quote=qmap.get(p.asset);const market=quote&&p.reliable?p.quantity*quote.price*100:null;const result=market!==null&&p.cost!==null?market-p.cost:null;return <tr key={`${p.asset}:${p.maturity||''}`}><td><div className="asset-cell"><AssetIcon asset={p.asset} logo={quote?.logo}/><span><b>{p.asset}</b><small>{quote?.name||p.broker}</small></span></div></td><td>{units(p.quantity)}</td><td>{money(p.cost)}</td><td>{money(market)}</td><td className={result===null?'':result<0?'negative':'positive'}>{money(result)}</td><td><button className="row-detail" onClick={()=>onDetails(p.asset)} aria-label={`Ver detalhes de ${p.asset}`}><ChevronRight size={15}/></button></td></tr>})}</tbody>)}</table></div></section>;
}
function AllocationDistribution({positions}:{positions:Position[]}){
 const [mode,setMode]=useState<'classes'|'sectors'>('classes');
 const {classes,sectors}=useMemo(()=>{const classMap=new Map<string,number>();const sectorMap=new Map<string,number>();for(const p of positions)if(p.cost){const assetClass=p.category==='Tesouro Direto'?'Renda fixa':p.category==='FII'?'Fundos imobiliários':'Ações';const sector=p.category==='Ação'?p.sector:p.category==='FII'?'Fundos imobiliários':'Títulos públicos';classMap.set(assetClass,(classMap.get(assetClass)||0)+p.cost);sectorMap.set(sector,(sectorMap.get(sector)||0)+p.cost);}const decorate=(map:Map<string,number>)=>[...map].sort((a,b)=>b[1]-a[1]).map(([name,value],i)=>({name,value,fill:palette[i%palette.length]}));return {classes:decorate(classMap),sectors:decorate(sectorMap)};},[positions]);
 const total=classes.reduce((s,p)=>s+p.value,0);
 const items=mode==='classes'?classes:sectors;
 const largest=items[0];return <section className="surface overview-donut"><div className="overview-section-head"><div><h2>Distribuição</h2><p>Composição pelo custo das posições abertas</p></div></div><div className="distribution-total-cards"><article><span>Total distribuído</span><b>{money(total)}</b><small>{positions.length} posições abertas</small></article><article><span>Maior participação</span><b>{largest?.name||'—'}</b><small>{largest&&total?pct(largest.value/total*100):'Sem base'}</small></article></div><div className="distribution-switch" role="group" aria-label="Forma de distribuição"><button aria-pressed={mode==='classes'} onClick={()=>setMode('classes')}>Classes de ativos</button><button aria-pressed={mode==='sectors'} onClick={()=>setMode('sectors')}>Distribuição setorial</button></div><div className="distribution-list"><div className="distribution-list-head"><span>{mode==='classes'?'Classe':'Setor'}</span><span>Valor</span><span>%</span></div>{items.map(p=><div key={p.name}><span><i style={{background:p.fill}}/>{p.name}</span><b>{money(p.value)}</b><strong>{total?pct(p.value/total*100):'—'}</strong><em><i style={{width:total?pct(p.value/total*100):'0%'}}/></em></div>)}</div><footer className="fixed-variable"><span>Renda variável <b>{pct(total?classes.filter(i=>i.name!=='Renda fixa').reduce((s,p)=>s+p.value,0)/total*100:0)}</b></span><span>Renda fixa <b>{pct(total?(classes.find(i=>i.name==='Renda fixa')?.value||0)/total*100:0)}</b></span></footer></section>;
}
function RealizedSales({data,onReview}:{data:Data;onReview:()=>void}){
 const sales=data.movements.filter(m=>m.side==='sell').sort((a,b)=>b.date.localeCompare(a.date));
 const positions=new Map(data.realizedPositions.map(p=>[[p.category,p.asset,p.maturity||''].join('|'),p]));
 const saleResult=(sale:Movement)=>{const position=positions.get([sale.category,sale.asset,sale.maturity||''].join('|'));const lots=position?.realizedDetail?.lots?.filter(l=>l.sellId===sale.id)||[];const matched=lots.reduce((sum,l)=>sum+l.quantity,0);return {position,lots,reliable:Math.abs(matched-Number(sale.quantity))<0.00000001&&!lots.some(l=>l.buyId.startsWith('bonus:')),result:lots.reduce((sum,l)=>sum+l.gross,0)};};
 const total=sales.reduce((sum,sale)=>{const row=saleResult(sale);return sum+(row.reliable?row.result:0);},0);
	 const groups=['Ação','FII','Tesouro Direto'].map(name=>{const rows=sales.filter(sale=>sale.category===name);const totals=rows.reduce((acc,sale)=>{const row=saleResult(sale);const cost=row.lots.reduce((sum,lot)=>sum+lot.cost,0);acc.gross+=sale.gross;acc.fees+=sale.costFees+sale.fees.irrf;if(row.reliable){acc.cost+=cost;acc.result+=row.result;acc.apuradas+=1;}return acc;},{gross:0,cost:0,fees:0,result:0,apuradas:0});return {name,rows,totals};}).filter(group=>group.rows.length);
	 return <section className="surface overview-sales"><div className="overview-section-head"><div><h2>Vendas apuradas</h2><p>Operações separadas por classe, incluindo registros que ainda exigem conferência.</p></div><div className="sales-total"><span>Resultado apurável</span><b>{money(total)}</b></div></div><div className="sales-table-scroll"><table><thead><tr><th>Data</th><th>Ativo</th><th>Qtd</th><th>Venda bruta</th><th>Custo FIFO</th><th>Taxas</th><th>Resultado</th><th>Status</th></tr></thead>{groups.map(group=><tbody key={group.name}><tr className="sales-group-row"><th colSpan={3}><span>{group.name}</span><small>{group.rows.length} vendas</small></th><th><small>Venda bruta</small><b>{money(group.totals.gross)}</b></th><th><small>Custo apurado</small><b>{money(group.totals.cost)}</b></th><th><small>Taxas</small><b>{money(group.totals.fees)}</b></th><th className={group.totals.result<0?'negative':'positive'}><small>Resultado</small><b>{money(group.totals.result)}</b></th><th aria-label="Status da classe" /></tr>{group.rows.map(sale=>{const {lots,reliable,result}=saleResult(sale);const cost=lots.reduce((sum,l)=>sum+l.cost,0);return <tr key={sale.id}><td>{sale.date.split('-').reverse().join('/')}</td><td><b>{sale.asset}</b><small>{sale.broker} · nota {sale.number}</small></td><td>{units(Number(sale.quantity))}</td><td>{money(sale.gross)}</td><td>{reliable?money(cost):'A conferir'}</td><td>{money(sale.costFees+sale.fees.irrf)}</td><td className={!reliable?'':result<0?'negative':'positive'}>{reliable?money(result):'A conferir'}</td><td><span className={`sale-status ${reliable?'done':'pending'}`}>{reliable?'Apurada':'Conferir'}</span></td></tr>})}</tbody>)}</table></div><div className="sales-footer"><span>{sales.length} operações de venda encontradas</span><button onClick={onReview}>Ver conferência <ChevronRight size={15}/></button></div></section>;
}
export function DashboardOverview({data,busy,onNewMovement,onReload,onReview,onPortfolio}:{data:Data;busy:boolean;onNewMovement:()=>void;onReload:()=>void;onReview:()=>void;onPortfolio:(asset:string)=>void}){
 const today=defaultEnd;const [start,setStart]=useState(defaultStart);const [end,setEnd]=useState(defaultEnd);const [history,setHistory]=useState<History|null>(null);const [loading,setLoading]=useState(true);const [selected,setSelected]=useState(['total','cdi','ibovespa']);const [periodicity,setPeriodicity]=useState<'monthly'|'weekly'|'annual'>('monthly');
 useEffect(()=>{const controller=new AbortController();fetch(`/api/benchmarks?start=${start}&end=${end}`,{signal:controller.signal}).then(async r=>{const value=await r.json() as History;if(!r.ok)throw new Error(value.error||'Falha ao carregar o histórico.');setHistory(value);}).catch(error=>{if(!controller.signal.aborted)setHistory({series:[],assetSeries:{},messages:[error instanceof Error?error.message:'Falha ao carregar o histórico.']});}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[start,end]);
 const positions=data.positions.filter(p=>p.quantity>0);const qmap=new Map(data.quotes.map(q=>[q.asset,q]));const applied=positions.reduce((s,p)=>s+(p.cost||0),0);const priced=positions.filter(p=>p.reliable&&p.cost!==null&&qmap.has(p.asset));const market=priced.reduce((s,p)=>s+p.quantity*qmap.get(p.asset)!.price*100,0);const comparable=priced.reduce((s,p)=>s+p.cost!,0);const returnPct=comparable?((market/comparable)-1)*100:null;const netProceeds=(data.cashEvents||[]).reduce((sum,event)=>sum+event.netCents,0);const returnWithProceeds=comparable?((market+netProceeds)/comparable-1)*100:null;
 const chart=useMemo(()=>{const all=new Map<string,Record<string,string|number>>();const add=(id:string,points:Point[])=>points.forEach(p=>all.set(p.date,{...(all.get(p.date)||{date:p.date}),[id]:p.value}));if(history){add('price',portfolioSeries(data.movements,history.assetSeries||{},false,start,end));add('total',portfolioSeries(data.movements,history.assetSeries||{},true,start,end));history.series.forEach(s=>add(s.id,normalizeBenchmark(s)));}const rows=[...all.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date)));const buckets=new Map<string,Record<string,string|number>>();for(const row of rows){const date=String(row.date),d=new Date(date+'T12:00:00Z');const week=Math.ceil((((d.getTime()-Date.UTC(d.getUTCFullYear(),0,1))/86400000)+new Date(Date.UTC(d.getUTCFullYear(),0,1)).getUTCDay()+1)/7),key=periodicity==='annual'?date.slice(0,4):periodicity==='monthly'?date.slice(0,7):`${d.getUTCFullYear()}-${String(week).padStart(2,'0')}`;buckets.set(key,row);}return [...buckets.values()];},[history,data.movements,start,end,periodicity]);
 const choices=[{id:'total',name:'Carteira · retorno total',color:'#12665b'},{id:'price',name:'Carteira · variação de preço',color:'#397f9f'},...(history?.series||[]).map((s,i)=>({id:s.id,name:s.name,color:palette[(i+1)%palette.length],available:s.available,message:s.message}))];
 const selectRange=(months:number|'month')=>{const finish=new Date(defaultEnd+'T12:00:00');const begin=months==='month'?new Date(finish.getFullYear(),finish.getMonth(),1):new Date(finish.getFullYear(),finish.getMonth()-months,finish.getDate());setLoading(true);setStart(begin.toISOString().slice(0,10));setEnd(defaultEnd);};
 return <div className="overview-dashboard"><div className="overview-filter"><div className="overview-actions"><button className="primary" onClick={onNewMovement}><Plus size={16}/>Nova movimentação</button><button onClick={onReload} disabled={busy}><RefreshCw size={15}/>{busy?'Recarregando…':'Recarregar dados'}</button></div><div className="date-presets" role="group" aria-label="Atalhos de período"><button onClick={()=>selectRange('month')}>Mês</button><button onClick={()=>selectRange(3)}>3 meses</button><button onClick={()=>selectRange(6)}>6 meses</button><button onClick={()=>selectRange(12)}>1 ano</button></div><label>De<input type="date" value={start} max={end} onChange={e=>{setLoading(true);setStart(e.target.value);}}/></label><label>Até<input type="date" value={end} min={start} max={today} onChange={e=>{setLoading(true);setEnd(e.target.value);}}/></label></div><section className="overview-totals"><article><div className="total-card-head"><span>Valor aplicado</span><i><WalletCards size={17}/></i></div><strong>{money(applied)}</strong><small>Custo histórico das posições abertas</small></article><article><div className="total-card-head"><span>Valor de mercado</span><i><Landmark size={17}/></i></div><strong>{money(market)}</strong><small>{priced.length} de {positions.length} ativos com preço disponível</small></article><article><div className="total-card-head"><span>Rentabilidade acumulada</span><i><TrendingUp size={17}/></i></div><strong className={returnPct!==null&&returnPct<0?'negative':'positive'}>{pct(returnPct)}</strong><small>Mercado comparado ao custo dos mesmos ativos</small></article><article><div className="total-card-head"><span>Rentabilidade com proventos</span><i><CircleDollarSign size={17}/></i></div><strong className={returnWithProceeds!==null&&returnWithProceeds<0?'negative':'positive'}>{pct(returnWithProceeds)}</strong><small>{money(netProceeds)} líquidos conciliados no extrato BTG</small></article></section>
 <section className="surface performance-card"><div className="overview-section-head"><div><h2>Performance de rentabilidade</h2><p>Retorno ponderado pelo tempo, comparado em base 0% no início do período.</p></div><button onClick={onReview}>Metodologia e pendências <ChevronRight size={15}/></button></div>{(history?.messages?.length||history?.message)&&<div className="market-coverage"><TriangleAlert size={15}/><span>{history?.message||history?.messages?.join(' · ')}</span></div>}<div className="performance-controls"><div className="benchmark-selector">{choices.map(c=><button key={c.id} title={'message' in c?c.message:undefined} disabled={'available' in c&&c.available===false} aria-pressed={selected.includes(c.id)} onClick={()=>setSelected(v=>v.includes(c.id)?v.filter(x=>x!==c.id):[...v,c.id])}><i style={{background:c.color}}/>{c.name}</button>)}</div><div className="periodicity-switch" role="group" aria-label="Periodicidade do gráfico">{([['monthly','Mensal'],['weekly','Semanal'],['annual','Anual']] as const).map(([id,label])=><button key={id} aria-pressed={periodicity===id} onClick={()=>setPeriodicity(id)}>{label}</button>)}</div></div><div className="performance-chart">{loading?<div className="chart-state">Lendo histórico de mercado…</div>:chart.length?<ResponsiveContainer width="100%" height={310}><LineChart data={chart} margin={{top:8,right:12,left:0,bottom:4}}><CartesianGrid vertical={false} stroke="#e8eeeb"/><ReferenceLine y={0} stroke="#9ba9a4"/><XAxis dataKey="date" tickFormatter={v=>periodicity==='annual'?String(v).slice(0,4):String(v).slice(5).split('-').reverse().join('/')} minTickGap={45}/><YAxis width={48} tickFormatter={v=>`${Number(v).toFixed(0)}%`}/><Tooltip labelFormatter={v=>String(v).split('-').reverse().join('/')} formatter={v=>`${Number(v).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}%`}/><Legend verticalAlign="bottom" height={28}/>{choices.filter(c=>selected.includes(c.id)).map(c=><Line key={c.id} type="monotone" dataKey={c.id} name={c.name} stroke={c.color} dot={false} activeDot={{r:3}} connectNulls strokeWidth={c.id==='total'?2.6:1.7}/>)}</LineChart></ResponsiveContainer>:<div className="chart-state">Não há preços históricos suficientes para calcular o período selecionado.</div>}</div><p className="chart-disclaimer">Periodicidade padrão: mensal. A alternância apenas consolida os dados armazenados e não gera novas chamadas. “Retorno total” usa fechamento ajustado; “variação de preço” usa fechamento sem ajuste.</p></section>
 <div className="overview-main-grid"><PortfolioList positions={positions} quotes={data.quotes} onDetails={onPortfolio}/><AllocationDistribution positions={positions}/></div>
 <RealizedSales data={data} onReview={onReview}/></div>;
}
