'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {Building2,BriefcaseBusiness,CreditCard,House,Plus,RefreshCw,ShieldCheck,ChevronRight} from 'lucide-react';
import {Button} from '@/components/ui/button';

type Role='master'|'admin'|'consultor'|'familia';
type Profile={id:string;display_name:string|null;role:Role;profile_code:string|null};
type Model={profile:Profile;profiles:Profile[];organizations:Array<{id:string;code:string;name:string;kind:string}>;organizationMembers:Array<{organization_id:string;profile_id:string;role:string}>;families:Array<{id:string;code:string;name:string;organization_id:string|null;supervisor_id:string}>;familyMembers:Array<{family_id:string;profile_id:string;family_role:string;relationship:string|null}>;invitations:Array<{id:string;email:string;role:string;display_name:string;status:string}>;subscriptions:Array<{id:string;subject_type:string;subject_id:string;plan_name:string;status:'active'|'inactive'}>;permissions:Array<{role:Role;permission:string;enabled:boolean}>};
const roles:Role[]=['master','admin','consultor','familia'];
const labels:Record<Role,string>={master:'Master',admin:'Administrador',consultor:'Consultor',familia:'Família'};
const permissionLabels:Record<string,string>={manage_organizations:'Gerenciar organizações',manage_users:'Gerenciar usuários',manage_subscriptions:'Gerenciar assinaturas',manage_families:'Gerenciar famílias',view_portfolios:'Visualizar carteiras',edit_portfolios:'Editar carteiras'};

export function ManagementDashboard(){
 const [data,setData]=useState<Model|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[section,setSection]=useState('overview');
 const load=()=>fetch('/api/management',{cache:'no-store'}).then(async r=>{const j=await r.json() as Model&{error?:string};if(!r.ok)throw new Error(j.error||'Falha ao carregar');setData(j);setError('');}).catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar'));
 useEffect(()=>{load();},[]);
 const mutate=async(body:object,key:string)=>{setBusy(key);try{const r=await fetch('/api/management',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json() as {error?:string};if(!r.ok)throw new Error(j.error);await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao atualizar');}finally{setBusy('');}};
 const maps=useMemo(()=>({profiles:new Map(data?.profiles.map(p=>[p.id,p])||[]),organizations:new Map(data?.organizations.map(o=>[o.id,o])||[]),families:new Map(data?.families.map(f=>[f.id,f])||[])}),[data]);
 if(error&&!data)return <main className="management-page"><p className="notice error">{error}</p><Button onClick={load}>Tentar novamente</Button></main>;
 if(!data)return <main className="management-page"><p className="surface">Carregando estrutura…</p></main>;
 const role=data.profile.role,consultants=data.profiles.filter(p=>p.role==='consultor');
 const centerTitle=role==='master'?'Central Master':role==='admin'?'Central da Organização':role==='consultor'?'Central do Consultor':'Visão da Família';
 const tabs=role==='master'?[['overview','Visão geral'],['organizations','Organizações'],['permissions','Permissões'],['subscriptions','Assinaturas']]:[['overview','Visão geral'],['people','Pessoas'],['families','Famílias']];
 const subjectName=(type:string,id:string)=>type==='organization'?maps.organizations.get(id)?.name:type==='familia'?maps.families.get(id)?.name:maps.profiles.get(id)?.display_name;
 return <main className="management-page">
  <header className="management-header"><div><p className="eyebrow">SAGRADO CAPITAL · {labels[role].toUpperCase()}</p><h1>{centerTitle}</h1><p>{role==='master'?'Operação, acessos e assinaturas do sistema.':role==='admin'?'Consultores e famílias vinculados à organização.':'Famílias sob sua responsabilidade.'}</p></div><div><Button variant="outline" onClick={load}><RefreshCw size={16}/>Atualizar</Button><Button asChild><Link href="/cadastro"><Plus size={16}/>Novo cadastro</Link></Button></div></header>
  <nav className="management-menu" aria-label="Seções da central">{tabs.map(([id,label])=><button key={id} aria-pressed={section===id} onClick={()=>setSection(id)}>{label}</button>)}</nav>
  {error&&<p className="notice error management-alert">{error}</p>}
  {section==='overview'&&<><section className="management-kpis"><article><Building2/><span>Organizações</span><strong>{data.organizations.length}</strong><small>Estruturas acessíveis</small></article><article><BriefcaseBusiness/><span>Consultores</span><strong>{consultants.length}</strong><small>Profissionais vinculados</small></article><article><House/><span>Famílias</span><strong>{data.families.length}</strong><small>Núcleos acompanhados</small></article><article><CreditCard/><span>Assinaturas ativas</span><strong>{data.subscriptions.filter(s=>s.status==='active').length}</strong><small>de {data.subscriptions.length} controladas</small></article></section><SimpleList title="Estrutura sob sua gestão" rows={[...data.organizations.map(o=>({id:o.id,name:o.name,type:'Organização',code:o.code,href:''})),...data.families.map(f=>({id:f.id,name:f.name,type:'Família',code:f.code,href:'/dashboard'}))]}/></>}
  {section==='organizations'&&role==='master'&&<section className="surface management-list"><h2>Organizações</h2><p className="note">Usuários e famílias ligados a cada estrutura.</p><table><thead><tr><th>Organização</th><th>Tipo</th><th>Admins</th><th>Consultores</th><th>Famílias</th><th></th></tr></thead><tbody>{data.organizations.map(o=>{const members=data.organizationMembers.filter(m=>m.organization_id===o.id);return <tr key={o.id}><td><b>{o.name}</b><small>{o.code}</small></td><td>{o.kind}</td><td>{members.filter(m=>m.role==='admin').length}</td><td>{members.filter(m=>m.role==='consultor').length}</td><td>{data.families.filter(f=>f.organization_id===o.id).length}</td><td><button>Gerenciar <ChevronRight size={13}/></button></td></tr>})}</tbody></table></section>}
  {section==='permissions'&&role==='master'&&<section className="surface management-list"><h2>Controle de permissões</h2><p className="note">Comportamento padrão de cada perfil.</p><table><thead><tr><th>Funcionalidade</th>{roles.map(r=><th key={r}>{labels[r]}</th>)}</tr></thead><tbody>{Object.entries(permissionLabels).map(([permission,label])=><tr key={permission}><td><b>{label}</b></td>{roles.map(r=>{const item=data.permissions.find(p=>p.role===r&&p.permission===permission),key=`${r}:${permission}`;return <td key={r}><button className={'permission-toggle '+(item?.enabled?'on':'')} disabled={busy===key||r==='master'} onClick={()=>mutate({type:'permission',role:r,permission,enabled:!item?.enabled},key)}>{item?.enabled?'Permitido':'Bloqueado'}</button></td>})}</tr>)}</tbody></table></section>}
  {section==='subscriptions'&&role==='master'&&<section className="surface management-list"><h2>Controle de assinaturas</h2><p className="note">Ativação manual preparada para futura automação pelo gateway de pagamento.</p><table><thead><tr><th>Assinante</th><th>Tipo</th><th>Plano</th><th>Status</th><th>Ação</th></tr></thead><tbody>{data.subscriptions.map(s=><tr key={s.id}><td><b>{subjectName(s.subject_type,s.subject_id)||'Cadastro vinculado'}</b></td><td>{s.subject_type}</td><td>{s.plan_name}</td><td><span className={'status-pill '+s.status}>{s.status==='active'?'Ativa':'Inativa'}</span></td><td><button disabled={busy===s.id} onClick={()=>mutate({type:'subscription',id:s.id,status:s.status==='active'?'inactive':'active'},s.id)}>{s.status==='active'?'Desativar':'Ativar'}</button></td></tr>)}</tbody></table></section>}
  {section==='people'&&role!=='master'&&<SimpleList title={role==='admin'?'Consultores da organização':'Titulares e dependentes'} rows={(role==='admin'?consultants:data.familyMembers.map(m=>maps.profiles.get(m.profile_id)).filter(Boolean) as Profile[]).map(p=>({id:p.id,name:p.display_name||'Sem nome',type:labels[p.role],code:p.profile_code||'Vinculado',href:''}))}/>}
  {section==='families'&&role!=='master'&&<SimpleList title="Famílias vinculadas" rows={data.families.map(f=>({id:f.id,name:f.name,type:f.organization_id?maps.organizations.get(f.organization_id)?.name||'Organização':'Ligação direta',code:f.code,href:'/dashboard'}))}/>}
  <footer><ShieldCheck size={14}/> Acesso atual: {labels[role]} · {data.profile.display_name}</footer>
 </main>;
}

function SimpleList({title,rows}:{title:string;rows:Array<{id:string;name:string;type:string;code:string;href:string}>}){return <section className="surface management-list"><h2>{title}</h2><p className="note">As funcionalidades ficam disponíveis em cada linha.</p><table><thead><tr><th>Nome</th><th>Tipo</th><th>Código ou vínculo</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.name}</b></td><td>{row.type}</td><td>{row.code}</td><td><span className="status-pill active">Ativo</span></td><td>{row.href?<Link href={row.href}>Abrir <ChevronRight size={13}/></Link>:<button>Detalhes <ChevronRight size={13}/></button>}</td></tr>)}</tbody></table></section>}
