'use client';
import {useEffect,useState,useCallback,useRef} from 'react';
import {useRouter} from 'next/navigation';
import {AppSidebar,type StorageInfo} from './app-shell';
import {ReconciliationPanel} from './reconciliation-panel';
import {DashboardOverview} from './dashboard-overview';
import {MovementsPanel} from './movements-panel';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Plus,RefreshCw,Download,ArrowUpRight,TriangleAlert,Upload} from 'lucide-react';
import {feeKeys,normalizeNote,type Note,type Trade,type FeeKey,consolidate} from '@/lib/ledger';
type Quote={asset:string;price:number;at:string;name?:string;symbol?:string;updated?:string;logo?:string|null};
type ImportBatch={id:string;fileName:string;status:string;totalDocuments:number;insertedDocuments:number;duplicateDocuments:number;rejectedDocuments:number;createdAt:string};
type Portfolio=ReturnType<typeof consolidate>&{notes:(Note&{updated?:string})[];quotes:Quote[];imports:ImportBatch[];storage:StorageInfo};
const labels:Record<FeeKey,string>={settlement:'Liquidação / B3',exchange:'Emolumentos',brokerage:'Corretagem',iss:'ISS',irrf:'IRRF'};
const money=(c:number|null|undefined)=>c==null?'A conferir':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100);
function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
const emptyTrade:Trade={asset:'',category:'Ação',side:'buy',quantity:'',price:''};
function blankNote():Note{return {id:crypto.randomUUID(),number:'',broker:'',date:new Date().toISOString().slice(0,10),kind:'variable',fees:{settlement:'0',exchange:'0',brokerage:'0',iss:'0',irrf:'0'},trades:[{...emptyTrade}]};}
export default function PortfolioApp({name,initialView="dashboard"}:{name:string;initialView?:string}){
 const router=useRouter();
 const [data,setData]=useState<Portfolio|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState(initialView),[filter]=useState('Todas'),[draft,setDraft]=useState<Note|null>(null),[formError,setFormError]=useState('');
 const [quick,setQuick]=useState(false),[assetClass,setAssetClass]=useState('Todas');
 const importInput=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{const r=await fetch('/api/portfolio',{cache:'no-store'});const j=await r.json() as Portfolio & {error:string};if(r.status===401){window.location.assign(new URL('/login',window.location.origin).href);return;}if(!r.ok)throw new Error(j.error);setData(j);setError('');},[]);
 useEffect(()=>{let mounted=true;const refresh=()=>{load().catch(e=>{if(mounted)setError(e.message);});};const timer=setTimeout(refresh,0);window.addEventListener('focus',refresh);const periodic=setInterval(()=>{if(document.visibilityState==='visible')refresh();},60000);return()=>{mounted=false;clearTimeout(timer);clearInterval(periodic);window.removeEventListener('focus',refresh);};},[load]);
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;
  if(!context)return;const lifecycle=new AbortController();
  try{context.registerTool({name:'show_portfolio_view',description:'Abre uma tela do consolidador sem alterar movimentações.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['dashboard','movimentacoes','conferencia']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const v=(input as {view:string})?.view;if(!['dashboard','movimentacoes','conferencia'].includes(v))throw new Error('Tela inválida');setTab(v);return {view:v};}},{signal:lifecycle.signal});}catch{ /* optional browser capability */ }
  return()=>lifecycle.abort();
 },[]);
 async function act(action:string,note?:Note){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/portfolio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,note})});const j=await r.json() as {error:string;message:string};if(!r.ok)throw new Error(j.error);await load();setMessage(j.message);setDraft(null);}catch(e){if(note)setFormError((e as Error).message);else setError((e as Error).message);}finally{setBusy(false);}}
 async function market(){setBusy(true);setMessage('');try{const r=await fetch('/api/market',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({force:true})});const j=await r.json() as {error:string;message:string};if(!r.ok)throw new Error(j.error);setMessage(j.message);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function importFile(file:File){setBusy(true);setError('');setMessage('');try{if(file.size>5_000_000)throw new Error('O arquivo ultrapassa o limite de 5 MB.');const parsed=JSON.parse(await file.text()) as {notes?:unknown[]}|unknown[];const documents=Array.isArray(parsed)?parsed:parsed.notes;if(!Array.isArray(documents))throw new Error('O JSON precisa conter uma lista “notes” ou ser uma lista de documentos.');const r=await fetch('/api/portfolio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'import',fileName:file.name,documents})});const j=await r.json() as {error?:string;message?:string};if(!r.ok)throw new Error(j.error||'Falha ao importar.');setMessage(j.message||'Importação concluída.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível ler o arquivo.');}finally{setBusy(false);if(importInput.current)importInput.current.value='';}}
 const trades=(data?.movements||[]).filter(t=>(filter==='Todas'||t.broker===filter)&&(assetClass==='Todas'||t.category===assetClass));
 const filteredNotes=(data?.notes||[]).filter(n=>(filter==='Todas'||n.broker===filter)&&(assetClass==='Todas'||n.trades.some(t=>t.category===assetClass)));
 let preview:ReturnType<typeof normalizeNote>=[];if(draft){try{preview=normalizeNote(draft);}catch{ /* draft is incomplete */ }}
 function updateTrade(i:number,patch:Partial<Trade>){setDraft(d=>d?{...d,trades:d.trades.map((t,j)=>j===i?{...t,...patch}:t)}:d);}
 function exportData(){if(!data)return;const blob=new Blob([JSON.stringify({format:'consolidador-v1',exportedAt:new Date().toISOString(),notes:data.notes,quotes:data.quotes},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='carteira-investimentos.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function editNote(note:Note){setFormError('');setQuick(false);setDraft(structuredClone(note));}
 return <div className="app-frame"><AppSidebar view={tab} name={name} issues={data?.issues.length||0} storage={data?.storage}/><main className="workspace app-workspace compact-workspace">
 {error&&<div role="alert" className="notice error">{error}<Button variant="outline" onClick={()=>load().catch(e=>setError(e.message))}>Tentar novamente</Button></div>}
 {message&&<p role="status" className="notice">{message}</p>}
 {!data&&!error&&<p role="status" className="surface">Carregando movimentações…</p>}
 {data&&!data.notes.length&&<section className="surface import"><div><p className="eyebrow">BASE INICIAL</p><h2>Importe seu histórico de investimentos</h2><p>Cada arquivo gera um lote auditável no Supabase. Documentos repetidos são preservados sem duplicação.</p><p className="note">Use um arquivo JSON exportado pelo sistema. Arquivos de corretoras serão adicionados por adaptadores específicos.</p></div><Button disabled={busy} onClick={()=>importInput.current?.click()}>{busy?'Importando…':'Selecionar arquivo'}</Button></section>}
 {data&&<>
 {tab!=='dashboard'&&<><div className="toolbar"><div className="broker"><span>Classe de ativo</span><Choice label="Filtrar classe de ativo" value={assetClass} onChange={setAssetClass} options={['Todas','Ação','FII','Tesouro Direto']}/></div><div className="actions"><small className="note">{data.quotes.length?`Mercado em cache · ${new Date(Math.max(...data.quotes.map(q=>q.updated?Date.parse(q.updated):0))).toLocaleString('pt-BR')}`:'Sem cotações armazenadas'}</small>{tab==='movimentacoes'&&<Button variant="outline" onClick={()=>importInput.current?.click()} disabled={busy}><Upload size={16}/>Importar notas</Button>}<Button variant="outline" onClick={market} disabled={busy}><RefreshCw size={16}/>Atualizar cotações</Button><Button variant="outline" onClick={exportData}><Download size={16}/>Exportar dados</Button></div></div>{tab==='movimentacoes'&&data.imports?.length>0&&<div className="import-history"><b>Última importação</b><span>{data.imports[0].fileName}</span><small>{data.imports[0].insertedDocuments} novos · {data.imports[0].duplicateDocuments} duplicados · {new Date(data.imports[0].createdAt).toLocaleString('pt-BR')}</small></div>}{data.issues.length>0&&<button className="review-strip" onClick={()=>setTab('conferencia')}><TriangleAlert size={18}/><span>{data.issues.length} pendências de conferência no histórico. Veja os documentos afetados.</span><ArrowUpRight size={18}/></button>}</>}
 <Tabs value={tab} onValueChange={setTab}><TabsContent value="dashboard"><DashboardOverview data={data} busy={busy} onNewMovement={()=>{setFormError('');setQuick(true);setDraft(blankNote());}} onReload={()=>load().catch(e=>setError(e.message))} onReview={()=>setTab('conferencia')} onPortfolio={asset=>router.push(`/ativos/${encodeURIComponent(asset)}`)}/></TabsContent>
 <TabsContent value="movimentacoes"><MovementsPanel movements={trades} notes={filteredNotes} onEdit={editNote}/></TabsContent>
 <TabsContent value="conferencia"><ReconciliationPanel data={data} onEdit={editNote}/></TabsContent>
 </Tabs></>}
 <input ref={importInput} hidden type="file" accept="application/json,.json" onChange={event=>{const file=event.target.files?.[0];if(file)void importFile(file);}}/><footer>Sagrado Capital <span>Consolidador de Investimentos · Cotações pela Brapi</span></footer>
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null);}}><DialogContent className="editor"><DialogHeader><DialogTitle>{draft?.version?'Editar documento':'Nova movimentação'}</DialogTitle><DialogDescription>{quick?'Registre uma compra ou venda. Se a nota tiver várias operações, use o modo completo para ratear as taxas.':'Cadastre todas as operações da nota e suas taxas totais. O rateio será automático.'}</DialogDescription></DialogHeader>{draft&&<form onSubmit={e=>{e.preventDefault();setFormError('');act('save',{...draft,number:draft.number.trim()||(quick?'MANUAL-'+draft.id.slice(0,8):'')});}}><Button type="button" variant="outline" disabled={!quick&&draft.trades.length>1} onClick={()=>setQuick(!quick)}>{quick?'Usar nota completa':'Usar lançamento rápido'}</Button><div className="form-grid"><label>Corretora<Input required maxLength={60} value={draft.broker} onChange={e=>setDraft({...draft,broker:e.target.value.toUpperCase()})}/></label><label>Nota / protocolo<Input required={!quick} placeholder={quick?'Opcional no lançamento rápido':'Número da nota'} maxLength={60} value={draft.number} onChange={e=>setDraft({...draft,number:e.target.value})}/></label><label>Data<Input type="date" required value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Mercado<Choice label="Mercado" value={draft.kind==='variable'?'Ações e FIIs':'Tesouro Direto'} options={['Ações e FIIs','Tesouro Direto']} onChange={v=>setDraft({...draft,kind:v==='Tesouro Direto'?'treasury':'variable',trades:draft.trades.map(t=>({...t,category:v==='Tesouro Direto'?'Tesouro Direto':'Ação'}))})}/></label></div>
 <h3>Operações da nota</h3>{draft.trades.map((t,i)=><div className="trade-editor" key={i}><div className="form-grid"><label>Ativo<Input required placeholder={draft.kind==='treasury'?'Tesouro Selic 2029':'PETR4'} value={t.asset} onChange={e=>updateTrade(i,{asset:draft.kind==='treasury'?e.target.value:e.target.value.toUpperCase()})}/></label><label>Categoria<Choice label="Categoria" value={t.category} options={draft.kind==='treasury'?['Tesouro Direto']:['Ação','FII']} onChange={v=>updateTrade(i,{category:v as Trade['category']})}/></label><label>Operação<Choice label="Operação" value={t.side==='buy'?'Compra / aporte':'Venda / resgate'} options={['Compra / aporte','Venda / resgate']} onChange={v=>updateTrade(i,{side:v==='Compra / aporte'?'buy':'sell'})}/></label><label>Quantidade<Input required type="number" step="0.00000001" min="0.00000001" value={t.quantity} onChange={e=>updateTrade(i,{quantity:e.target.value})}/></label><label>Preço unitário (R$)<Input required type="number" step="0.00000001" min="0.00000001" value={t.price} onChange={e=>updateTrade(i,{price:e.target.value})}/></label>{draft.kind==='treasury'&&<label>Vencimento<Input required type="date" value={t.maturity||''} onChange={e=>updateTrade(i,{maturity:e.target.value})}/></label>}</div><div className="trade-foot"><span>{preview[i]?`Taxas: ${money(preview[i].costFees)} · IRRF: ${money(preview[i].fees.irrf)}`:'Preencha quantidade e preço para ver o rateio.'}</span>{draft.trades.length>1&&<Button type="button" variant="ghost" onClick={()=>setDraft({...draft,trades:draft.trades.filter((_,j)=>j!==i)})}>Remover operação</Button>}</div></div>)}<Button hidden={quick} type="button" variant="outline" onClick={()=>setDraft({...draft,trades:[...draft.trades,{...emptyTrade,category:draft.kind==='treasury'?'Tesouro Direto':'Ação'}]})}><Plus size={16}/>Adicionar operação</Button><details open={!quick}><summary>Taxas totais do documento (R$) · opcionais no lançamento rápido</summary><div className="form-grid">{feeKeys.map(k=><label key={k}>{labels[k]}<Input required type="number" min="0" step="0.01" value={draft.fees[k]} onChange={e=>setDraft({...draft,fees:{...draft.fees,[k]:e.target.value}})}/></label>)}</div></details><p className="note">No Tesouro, informe a taxa B3 em “Liquidação / B3”. IR e IOF não estão contemplados nesta versão.</p>{formError&&<p role="alert" className="notice error">{formError}</p>}<div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setDraft(null)}>Cancelar</Button><Button type="submit" disabled={busy}>{busy?'Salvando…':'Salvar e recalcular'}</Button></div></form>}</DialogContent></Dialog>
 </main></div>;
}
