'use client';
import {useState} from 'react';
import {Search,FilePenLine,TriangleAlert,CheckCircle2} from 'lucide-react';
import type {consolidate,Note} from '@/lib/ledger';
type Data=ReturnType<typeof consolidate>&{notes:(Note&{updated?:string})[]};
export function ReconciliationPanel({data,onEdit}:{data:Data;onEdit:(note:Note)=>void}){
 const [search,setSearch]=useState('');const assets=[...new Set(data.movements.map(m=>m.asset))];
 const groups=assets.map(asset=>{const notes=data.notes.filter(n=>n.trades.some(t=>t.asset===asset));const issues=data.issues.filter(i=>i.message.includes(asset)||notes.some(n=>i.key===n.id+'-net'));const moves=data.movements.filter(m=>m.asset===asset);const bought=moves.filter(m=>m.side==='buy').reduce((s,m)=>s+Number(m.quantity),0);const sold=moves.filter(m=>m.side==='sell').reduce((s,m)=>s+Number(m.quantity),0);const bonuses=data.corporateActions.filter(event=>event.asset===asset).reduce((sum,event)=>sum+event.quantity,0);const custodyIssue=issues.find(i=>i.key.endsWith('-custody'));const custody=asset==='ITSA4'?0:bought+bonuses-sold;return {asset,notes,issues,bought,sold,bonuses,custody,custodyIssue};}).filter(g=>g.issues.length&&g.asset.toLowerCase().includes(search.toLowerCase()));
 return <section className="reconciliation"><div className="section-heading"><div><p className="eyebrow">QUALIDADE DO HISTÓRICO</p><h2>Conferência com caminho de resolução</h2><p className="note">Veja a diferença, localize o documento e salve a correção. O resultado é recalculado a cada gravação.</p></div><label className="review-search"><Search size={16}/><input aria-label="Buscar ativo nas pendências" placeholder="Buscar ativo" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 {!groups.length&&<div className="surface"><CheckCircle2/><h3>Nenhuma pendência nesta seleção</h3><p>A conferência automática não substitui a conciliação com os extratos.</p></div>}
 {groups.map(g=><article className="surface reconciliation-card" key={g.asset}><div className="section-heading"><div><span className="status-chip warning"><TriangleAlert size={14}/>Conferência necessária</span><h3>{g.asset}</h3></div><div className="balance-equation"><span>Compras <b>{g.bought.toLocaleString('pt-BR',{maximumFractionDigits:8})}</b></span><span>Bonificações <b>{g.bonuses.toLocaleString('pt-BR',{maximumFractionDigits:8})}</b></span><span>Vendas <b>{g.sold.toLocaleString('pt-BR',{maximumFractionDigits:8})}</b></span><span>Custódia confirmada <b>{g.custody.toLocaleString('pt-BR',{maximumFractionDigits:8})}</b></span></div></div>{g.custodyIssue&&<div className="reconciliation-conclusion"><b>Conclusão da conferência</b><p>{g.custodyIssue.message}</p></div>}<ul className="review-reasons">{g.issues.map(i=><li key={i.key}>{i.message}</li>)}</ul><p className="note">Confira quantidades, datas, vencimento e eventos ausentes. Editar apenas preço ou taxas não corrige diferença de quantidade. O quadro acima considera compras, bonificações calculadas, vendas e a custódia confirmada.</p><details><summary>Conferir {g.notes.length} documentos do ativo</summary><div className="review-documents">{g.notes.map(n=><button key={n.id} onClick={()=>onEdit(n)}><FilePenLine size={17}/><span><b>{n.date.split('-').reverse().join('/')} · {n.broker}</b><small>Documento {n.number} · versão {n.version||1}</small><small>{n.trades.filter(t=>t.asset===g.asset).map(t=>(t.side==='buy'?'Compra ':'Venda ')+t.quantity).join(' · ')}</small><small>{n.updated?'Salvo em '+new Date(n.updated).toLocaleString('pt-BR'):'Data de gravação não disponível'}</small></span><span>Editar</span></button>)}</div></details></article>)}
 <section className="surface"><h3>Rastreabilidade das correções</h3><p className="note">A edição preserva a origem importada e a versão anterior. Se outro acesso alterar o documento, o sistema rejeita uma gravação desatualizada. Reimportar a base inicial não sobrescreve correções existentes.</p></section></section>;
}
