'use client';
/* eslint-disable @next/next/no-html-link-for-pages -- Hosted sign-in requires top-level navigation. */
import {useState} from 'react';
import {LockKeyhole,ArrowRight} from 'lucide-react';
export function LoginForm({configured}:{configured:boolean}){
 const [mode,setMode]=useState<'login'|'signup'>('login');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const fields=new FormData(e.currentTarget);
  try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,email:fields.get('email'),password:fields.get('password')})});const j=await r.json() as {error?:string;confirmation?:boolean};if(!r.ok)throw new Error(j.error);if(j.confirmation)setMessage('Confira sua caixa de entrada para confirmar o e-mail. Depois, entre com sua senha.');else window.location.assign(new URL('/',window.location.origin).href);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}
 }
 return <div className="login-form"><div className="login-lock"><LockKeyhole size={24}/></div><p className="eyebrow">SEU ESPAÇO DE INVESTIMENTOS</p><h2>{mode==='login'?'Bem-vindo de volta.':'Comece sua organização.'}</h2><p className="muted">Acesse sua carteira e acompanhe cada decisão com mais clareza.</p>{configured?<><form onSubmit={submit}><label>E-mail<input name="email" type="email" autoComplete="email" required placeholder="voce@exemplo.com"/></label><label>Senha<input name="password" type="password" minLength={8} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'} required placeholder="Pelo menos 8 caracteres"/></label><button className="primary" disabled={busy}>{busy?'Aguarde…':mode==='login'?'Entrar na minha carteira':'Criar conta'}<ArrowRight size={18}/></button></form><button className="login-switch" onClick={()=>{setMode(mode==='login'?'signup':'login');setMessage('');}}>{mode==='login'?'Primeiro acesso? Criar conta':'Já tem conta? Entrar'}</button></>:<div className="notice"><p>A conexão com Supabase está em preparação. A carteira existente permanece disponível no ambiente local.</p><a className="primary" href="/signin-with-chatgpt?return_to=/" target="_top">Abrir carteira local</a></div>}{message&&<p role="status" className="notice">{message}</p>}<small>Seus registros são privados. Cada conta acessa somente sua própria carteira.</small></div>;
}
