import fs from 'node:fs';
fs.writeFileSync('app/page.tsx', `import { getChatGPTUser, chatGPTSignInPath } from './chatgpt-auth';
export const dynamic = 'force-dynamic';
export default async function Home() {
 const user = await getChatGPTUser();
 return <main className="workspace"><header><b>Í / INVESTIMENTOS</b><span>Consolidador pessoal</span></header><section className="intro"><p>CARTEIRA CONSOLIDADA</p><h1>Seu histórico.<br/>Uma visão completa.</h1><p>Ações, fundos imobiliários e Tesouro Direto, reunidos por ativo e corretora.</p></section><section className="surface"><h2>{user ? 'Preparação da carteira' : 'Acesse sua carteira'}</h2><p>Movimentações preservadas, taxas proporcionais e conferência de saldos.</p>{!user && <a className="primary" href={chatGPTSignInPath('/')} target="_top">Entrar com ChatGPT</a>}<div className="metrics"><div><strong>112</strong><span>Movimentações de ações e FIIs na fonte</span></div><div><strong>28</strong><span>Movimentações de Tesouro Direto na fonte</span></div><div><strong>4</strong><span>Corretoras na fonte</span></div></div><p className="note">A importação será acompanhada de uma conferência. Saldos com movimentações faltantes não serão apresentados como posições confirmadas.</p></section></main>
}`);
let css=fs.readFileSync('app/globals.css','utf8').replace('--primary: #171717','--primary: #164cb2').replace('--background: #ffffff','--background: #f3f6fb').replace('--foreground: #171717','--foreground: #182c49').replace(/@media \(prefers-color-scheme: dark\) \{[\s\S]*?\r?\n\}\r?\n/,'');
css+=`.workspace{max-width:1280px;margin:auto;padding:32px}header{display:flex;justify-content:space-between;border-bottom:1px solid #d8e1ee;padding-bottom:24px;gap:16px}header b{letter-spacing:.15em}.intro{padding:48px 0 28px}.intro>p:first-child{font-size:14px;letter-spacing:.12em;color:#164cb2;font-weight:700}h1{font-size:44px;line-height:1.12;font-weight:600;margin:12px 0 20px;letter-spacing:-.03em}h2{font-size:24px;font-weight:600;margin-bottom:12px}p{line-height:1.6}.surface{background:white;border:1px solid #d8e1ee;border-radius:12px;padding:32px}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:24px;margin:32px 0}.metrics>div{border-left:3px solid #164cb2;padding-left:20px}.metrics strong{font-size:32px;display:block}.metrics span{font-size:14px;color:#53647c}.primary{display:inline-block;background:#164cb2;color:white;padding:12px 20px;border-radius:7px;margin-top:20px;font-weight:600}.note{font-size:14px;color:#53647c}@media(max-width:640px){.workspace{padding:20px}.metrics{grid-template-columns:1fr}h1{font-size:34px}.surface{padding:22px}header{flex-direction:column}}`;
fs.writeFileSync('app/globals.css',css);
fs.writeFileSync('app/layout.tsx',fs.readFileSync('app/layout.tsx','utf8').replace('Starter Project','Consolidador de investimentos').replace('A clean starting point for building your site.','Ações, fundos imobiliários e Tesouro Direto em uma carteira.').replace('lang="en"','lang="pt-BR"'));
fs.writeFileSync('public/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="7" fill="#142e55"/><path d="M8 23V16h4v7m2 0V11h4v12m2 0V6h4v17" stroke="#fff" stroke-width="2"/></svg>');
