import {getUser} from '@/lib/auth';
import {database} from '@/db/store';
import {supabaseConfigured,supabaseServer} from '@/lib/supabase/server';
import {z} from 'zod';
const schema=z.object({id:z.string().uuid().optional(),asset:z.string().trim().min(1).max(100),kind:z.enum(['bonus','split','reverse_split','subscription','transfer','other']),eventDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),factor:z.number().positive().finite().optional(),label:z.string().trim().min(1).max(300),source:z.string().max(2000).optional(),notes:z.string().max(5000).optional()});
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'private, no-store'}});
async function ensureTable(){await database().prepare(`CREATE TABLE IF NOT EXISTS asset_events (id TEXT PRIMARY KEY, owner TEXT NOT NULL, asset TEXT NOT NULL, kind TEXT NOT NULL, event_date TEXT NOT NULL, factor REAL, label TEXT NOT NULL, source TEXT, notes TEXT, updated TEXT NOT NULL)`).run();}
export async function GET(req:Request){const user=await getUser();if(!user)return json({error:'Entre para consultar eventos.'},401);const asset=new URL(req.url).searchParams.get('asset');try{
 if(supabaseConfigured()){const db=await supabaseServer();let q=db.from('corporate_events').select('*').eq('owner_id',user.userId).order('event_date',{ascending:false});if(asset)q=q.eq('asset',asset);const {data,error}=await q;if(error)throw error;return json({events:data});}
 await ensureTable();const q=asset?database().prepare('SELECT * FROM asset_events WHERE owner=? AND asset=? ORDER BY event_date DESC').bind(user.userId,asset):database().prepare('SELECT * FROM asset_events WHERE owner=? ORDER BY event_date DESC').bind(user.userId);return json({events:(await q.all()).results});
 }catch{return json({error:'Não foi possível consultar os eventos.'},503);}}
export async function POST(req:Request){const user=await getUser();if(!user)return json({error:'Entre para registrar eventos.'},401);if(req.headers.get('origin')!==new URL(req.url).origin)return json({error:'Origem não permitida.'},403);try{
 const parsed=schema.safeParse(await req.json());if(!parsed.success)return json({error:'Revise os dados do evento.'},400);const b=parsed.data;const id=b.id||crypto.randomUUID();
 if(supabaseConfigured()){const db=await supabaseServer();const row={asset:b.asset.toUpperCase(),kind:b.kind,event_date:b.eventDate,factor:b.factor??null,label:b.label,source:b.source??'manual',notes:b.notes??'',updated_at:new Date().toISOString()};const result=b.id?await db.from('corporate_events').update(row).eq('id',id).eq('owner_id',user.userId).select('id').single():await db.from('corporate_events').insert({...row,id,owner_id:user.userId}).select('id').single();if(result.error)return json({error:'Não foi possível salvar este evento.'},400);return json({id});}
 await ensureTable();const result=await database().prepare('INSERT INTO asset_events(id,owner,asset,kind,event_date,factor,label,source,notes,updated) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET asset=excluded.asset,kind=excluded.kind,event_date=excluded.event_date,factor=excluded.factor,label=excluded.label,source=excluded.source,notes=excluded.notes,updated=excluded.updated WHERE asset_events.owner=excluded.owner').bind(id,user.userId,b.asset.toUpperCase(),b.kind,b.eventDate,b.factor??null,b.label,b.source??'manual',b.notes??'',new Date().toISOString()).run();if(!result.meta.changes)return json({error:'Evento não encontrado.'},404);return json({id});
 }catch{return json({error:'Não foi possível salvar o evento.'},400);}}
export async function DELETE(req:Request){const user=await getUser();if(!user)return json({error:'Entre para remover eventos.'},401);if(req.headers.get('origin')!==new URL(req.url).origin)return json({error:'Origem não permitida.'},403);const id=new URL(req.url).searchParams.get('id');if(!id)return json({error:'Informe o evento.'},400);try{if(supabaseConfigured()){const db=await supabaseServer();const {error}=await db.from('corporate_events').delete().eq('id',id).eq('owner_id',user.userId);if(error)throw error;}else{await ensureTable();await database().prepare('DELETE FROM asset_events WHERE id=? AND owner=?').bind(id,user.userId).run();}return json({ok:true});}catch{return json({error:'Não foi possível remover o evento.'},503);}}
